[2022-03-05  13:33:04.521] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-05  13:40:50.455] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-05  13:54:25.364] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-05  13:54:25.429] -> [DEBUG]: 
配置文件内容：
{'extensions': {'extensions_name': 'gqgm'}, 'connect': {'server_addr': '127.0.0.1', 'server_api_port': '5701', 'server_event_port': '5700'}, 'debug': {'print_rev': '0', 'log_file_name': 'gqapi.log', 'file_log_level': 'info', 'console_log_level': 'info'}}
[2022-03-05  13:54:25.713] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-05  13:54:25.733] -> [DEBUG]: 

[2022-03-05  18:11:17.566] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-05  18:11:17.570] -> [CRITICAL]: 
日志设置加载错误：
<class 'Exception'>
[2022-03-05  18:11:18.810] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-05  18:11:18.818] -> [CRITICAL]: 
日志设置加载错误：
<class 'Exception'>
[2022-03-06  18:01:53.963] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-06  18:01:54.002] -> [DEBUG]: 
debug
[2022-03-06  18:01:54.008] -> [INFO]: 
info
[2022-03-06  18:01:54.009] -> [WARNING]: 
warning
[2022-03-06  18:01:54.224] -> [ERROR]: 
error
[2022-03-06  18:01:54.716] -> [CRITICAL]: 
critical
[2022-03-06  18:01:54.885] -> [DEBUG]: 
debug
[2022-03-06  18:01:54.929] -> [INFO]: 
info
[2022-03-06  18:01:55.110] -> [WARNING]: 
warning
[2022-03-06  18:01:55.119] -> [ERROR]: 
error
[2022-03-06  18:01:55.161] -> [CRITICAL]: 
critical
[2022-03-06  18:01:55.313] -> [DEBUG]: 
debug
[2022-03-06  18:01:55.320] -> [INFO]: 
info
[2022-03-06  18:01:55.473] -> [WARNING]: 
warning
[2022-03-06  18:01:55.473] -> [ERROR]: 
error
[2022-03-06  18:01:55.768] -> [CRITICAL]: 
critical
[2022-03-06  18:01:55.800] -> [DEBUG]: 
debug
[2022-03-06  18:01:56.052] -> [INFO]: 
info
[2022-03-06  18:01:56.055] -> [WARNING]: 
warning
[2022-03-06  18:01:56.062] -> [ERROR]: 
error
[2022-03-06  18:01:56.179] -> [CRITICAL]: 
critical
[2022-03-06  18:01:56.282] -> [DEBUG]: 
debug
[2022-03-06  18:01:56.307] -> [INFO]: 
info
[2022-03-06  18:01:56.531] -> [WARNING]: 
warning
[2022-03-06  18:01:56.565] -> [ERROR]: 
error
[2022-03-06  18:01:56.785] -> [CRITICAL]: 
critical
[2022-03-07  13:22:57.799] -> [ERROR]: 
日志等级配置错误，将默认使用DEBUG等级！
[2022-03-07  13:22:57.902] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-07  13:22:57.902] -> [DEBUG]: 
ok
[2022-03-07  13:23:23.460] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-07  13:23:23.460] -> [DEBUG]: 
ok
[2022-03-07  13:23:44.840] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-07  13:23:44.871] -> [DEBUG]: 
ok
[2022-03-07  13:29:32.885] -> [ERROR]: 
DEBUGI日志等级配置错误，将默认使用DEBUG等级！
[2022-03-07  13:29:32.892] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-07  13:29:33.038] -> [DEBUG]: 
ok
[2022-03-07  13:30:23.941] -> [ERROR]: 
<StreamHandler <stderr> (DEBUG)>日志等级配置错误，将默认使用DEBUG等级！
[2022-03-07  13:30:24.198] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-07  13:30:24.200] -> [DEBUG]: 
ok
[2022-03-07  13:31:25.705] -> [ERROR]: 
DEBUGI 日志等级配置错误，将默认使用DEBUG等级！
[2022-03-07  13:31:25.726] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-07  13:31:25.911] -> [DEBUG]: 
ok
[2022-03-07  13:32:28.209] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-07  13:34:09.473] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-07  13:36:52.448] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-07  13:36:52.735] -> [CRITICAL]: 
  File "c:/Users/admin/Desktop/项目/GQAPI/main.py", line 10, in <module>
    Set_Log(log_file_name=settings['debug']['log_file_name'], file_log_level=settings['debug']['file_log_level'], console_log_level=settings['debug']['console_log_level']) # 初始化日志模块
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)

[2022-03-07  13:41:25.644] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-03-07  13:41:26.125] -> [CRITICAL]: 
Traceback (most recent call last):
  File "c:/Users/admin/Desktop/项目/GQAPI/main.py", line 10, in <module>
    Set_Log(log_file_name=settings['debug']['log_file_name'], file_log_level=settings['debug']['file_log_level'], console_log_level=settings['debug']['console_log_level']) # 初始化日志模块
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'file_log_level'

